apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-django-task
spec:
  workspaces:
    - name: source
  steps:
    - name: deploy-django
      image: bitnami/kubectl:latest
      script: |
        kubectl apply -f /workspace/source/deployment-django.yaml

