apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1  # Number of desired pods
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: shivam424/django:latest  # Docker image
          ports:
            - containerPort: 8000  # Port that application listens on
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
          volumeMounts:
            - name: sqlite-data
              mountPath: /data  # Path in the container to mount the volume
      volumes:
        - name: sqlite-data
          persistentVolumeClaim:
            claimName: sqlite-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: django