services:
  flask-ml:
    container_name: flask-ml
    image: shivam424/flask:latest
    ports:
      - "5001:5000"
    networks:
      - elk

  django:
    container_name: django
    image: shivam424/django:latest
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/data
    depends_on:
      - flask-ml
    networks:
      - elk


  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  Logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    # volumes:
    #   - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - Elasticsearch
    ports:
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  Kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - Elasticsearch
    networks:
      - elk

networks:
  elk:

volumes:
  sqlite_data:
  elastic_data: {}
